### Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.
It is the fundamental package for scientific computing with Python

### What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. 
While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [7]:
### firstly to install numpy in jupyter 

### pip install numpy

In [8]:
## initially Lets import numpy

import numpy as np

In [9]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [10]:
print(arr)

[1 2 3 4 5]


In [11]:
type(arr)

numpy.ndarray

In [12]:
### above array is an one deminsional arry

In [13]:
arr.shape

(5,)

In [14]:
### since the above arry is one dimensional to conert the one dimensional arry into two dimensional array we use reshape.

In [16]:
# first to reshape craete an 2 dimensional array
## Multinested array

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [17]:
#in 2 dimensional arry we will be having 2 square barckets [[]]
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
type(arr)

numpy.ndarray

In [19]:
## check the shape of the array

arr.shape

(3, 5)

In [20]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

### Indexing

In [21]:
## accessing the array elements

arr=np.array([1,2,3,4,5,6,7,8,9])

In [22]:
arr[3]

4

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [25]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [26]:
#just using coln the array is displayed : pickup all teh rows and columns
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [27]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [28]:
arr[1:, 3:]

array([[5, 6],
       [8, 9]])

In [29]:
arr[1:,2:]

array([[4, 5, 6],
       [6, 8, 9]])

In [30]:
arr[1:,1:]

array([[3, 4, 5, 6],
       [7, 6, 8, 9]])

In [31]:
#arange([start,] stop[, step,], dtype=None, *, like=None)

#Return evenly spaced values within a given interval.

arr=np.arange(0,10,step=2)

In [32]:
arr

array([0, 2, 4, 6, 8])

In [34]:
#linspace is equal divided

np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [35]:
#Copy Function & braodcasting

In [36]:
arr[3:]=100

In [37]:
arr

array([  0,   2,   4, 100, 100])

In [38]:
arr1=arr

In [40]:
arr1[3:]=500
print(arr1)

[  0   2   4 500 500]


In [41]:
arr

array([  0,   2,   4, 500, 500])

In [43]:
#array is actually an referrence type

In [44]:
arr1=arr.copy()

In [ ]:
#the below is just craeting an another memory space to store the array values.

In [45]:
print(arr)
arr1[3:]=1000
print(arr1)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [46]:
arr

array([  0,   2,   4, 500, 500])

In [48]:
### Some conditions very useful in Exploratory Data Analysis 

val=2
arr<2

array([ True, False, False, False, False])

In [49]:
val=2
arr*2

array([   0,    4,    8, 1000, 1000])

In [51]:
val=2
arr/2

array([  0.,   1.,   2., 250., 250.])

In [52]:
val=2
arr[arr<3]

array([0, 2])

In [53]:
#np.ones craete an array where all the elements are basically by 1
#Signature: np.ones(shape, dtype=None, order='C', *, like=None)
#Docstring:
#Return a new array of given shape and type, filled with ones

In [56]:
np.ones(4)

array([1., 1., 1., 1.])

In [57]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [58]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
## random distribution --> selects the random vales of given sheet
np.random.rand(3,3)

array([[0.51224566, 0.7059086 , 0.24749249],
       [0.3058419 , 0.3370483 , 0.82107276],
       [0.21239639, 0.83898447, 0.01951711]])

In [60]:
#randn --> Return a sample (or samples) from the "standard normal" distribution.

arr_ex=np.random.randn(4,4)

In [61]:
arr_ex

array([[-1.26006045, -0.74054564, -2.00155368, -2.58020049],
       [-1.02444875, -0.35007973,  0.88221024,  1.50693149],
       [-0.21883887,  0.50646755, -0.49191614, -0.49788848],
       [-2.18146745,  0.78429574,  0.59199505, -2.65912394]])